function [wav, spec, A, int, inc] = loadCudaBimSim(dir,absSpecFileName, absImageFileName,intensityFile, incidentFile, rows,cols, add)
% load data generated by cuda bimsim

if ~isempty(absSpecFileName)
    absSpecData = csvread([dir absSpecFileName]);
    wav = absSpecData(:,1);
else
    wav=1;
end
A=[];
if ~isempty(absImageFileName)
    A = fread(fopen([dir absImageFileName]),rows*cols*numel(wav),'*float32');
    A = reshape(A,rows,cols,numel(wav));
end
int=[]; inc=[]; spec=[];
if ~isempty(intensityFile)
    int = fread(fopen([dir intensityFile]),rows*cols*numel(wav),'*float32');
    int = reshape(int,rows,cols,numel(wav));
end

if ~isempty(incidentFile)
    inc = fread(fopen([dir incidentFile]),rows*cols*numel(wav),'*float32');
    inc = reshape(inc,rows,cols,numel(wav));
end

if ~isempty(A)
    spec = zeros(size(wav));
    numWav = numel(wav);
    r_idx = round((rows+1)/2);
    c_idx = round((cols+1)/2);
    [r,c,~] = ind2sub(size(A),find(A == max(A(:))));
    
    if add==1
        if ~isempty(absSpecFileName)
            spec = absSpecData(:,2);
        end
    elseif add ==2
        for i=1:numWav
            temp = A(:,:,i);
            spec(i) = temp(r_idx, c_idx);
        end
    else
        spec = squeeze(A(r,c,:));
    end
    
end